// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwcI-isGQmM15n9EFkMe_YlxRHoX44ejc',
    appId: '1:698666747322:web:967717dff30aa8f85dc983',
    messagingSenderId: '698666747322',
    projectId: 'pdouvch-sandbox-app',
    authDomain: 'pdouvch-sandbox-app.firebaseapp.com',
    storageBucket: 'pdouvch-sandbox-app.appspot.com',
    measurementId: 'G-G5YHE4MWNN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzjaiu-QugzG5Y7zHZTGdOBZghh7_k5Yk',
    appId: '1:698666747322:android:dab963fa45eaf4ef5dc983',
    messagingSenderId: '698666747322',
    projectId: 'pdouvch-sandbox-app',
    storageBucket: 'pdouvch-sandbox-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHv1OQcNA-oueMXS5aSAUIR4z-ChbsGyE',
    appId: '1:698666747322:ios:27c4ebbdd902e3c25dc983',
    messagingSenderId: '698666747322',
    projectId: 'pdouvch-sandbox-app',
    storageBucket: 'pdouvch-sandbox-app.appspot.com',
    iosBundleId: 'com.pdouvch.sandboxapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHv1OQcNA-oueMXS5aSAUIR4z-ChbsGyE',
    appId: '1:698666747322:ios:27c4ebbdd902e3c25dc983',
    messagingSenderId: '698666747322',
    projectId: 'pdouvch-sandbox-app',
    storageBucket: 'pdouvch-sandbox-app.appspot.com',
    iosBundleId: 'com.pdouvch.sandboxapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwcI-isGQmM15n9EFkMe_YlxRHoX44ejc',
    appId: '1:698666747322:web:b552fb37dac929575dc983',
    messagingSenderId: '698666747322',
    projectId: 'pdouvch-sandbox-app',
    authDomain: 'pdouvch-sandbox-app.firebaseapp.com',
    storageBucket: 'pdouvch-sandbox-app.appspot.com',
    measurementId: 'G-CN03SDEMC4',
  );

}